##OROV SimPlots##
##B Gutierrez##
##January 2019##

#Set working directory and load ggplot2 library
setwd("/Users/user/Documents/DPhil_Research/OROV_America/OROV_Recombination")
getwd()
library('adegenet')
library('ape')
library('spider')
library('ggplot2')

#Import sequences and transform to DNAbin object
L1.seqs <- fasta2DNAbin('OROV_v_IQTV_L_BRA1960.fasta')
L2.seqs <- fasta2DNAbin('OROV_v_IQTV_L_BRA2000.fasta')
L3.seqs <- fasta2DNAbin('OROV_v_IQTV_L_BRA2009.fasta')
L4.seqs <- fasta2DNAbin('OROV_v_IQTV_L_PAN1999.fasta')
L5.seqs <- fasta2DNAbin('OROV_v_IQTV_L_ECU2016.fasta')
L6.seqs <- fasta2DNAbin('OROV_v_IQTV_L_PAN1989.fasta')
L7.seqs <- fasta2DNAbin('OROV_v_IQTV_L_PER2000.fasta')
L8.seqs <- fasta2DNAbin('OROV_v_IQTV_L_PER2008.fasta')

G1a.seqs <- fasta2DNAbin('OROV_v_IQTV_M_G1_BRA1960.fasta')
G1b.seqs <- fasta2DNAbin('OROV_v_IQTV_M_G1_BRA2000.fasta')
G1c.seqs <- fasta2DNAbin('OROV_v_IQTV_M_G1_BRA2009.fasta')
G1d.seqs <- fasta2DNAbin('OROV_v_IQTV_M_G1_PAN1999.fasta')
G2a.seqs <- fasta2DNAbin('OROV_v_IQTV_M_G2_ECU2016.fasta')
G2b.seqs <- fasta2DNAbin('OROV_v_IQTV_M_G2_PAN1989.fasta')
G2c.seqs <- fasta2DNAbin('OROV_v_IQTV_M_G2_PER2000.fasta')
G2d.seqs <- fasta2DNAbin('OROV_v_IQTV_M_G2_PER2008.fasta')

S1.seqs <- fasta2DNAbin('OROV_v_IQTV_S_BRA1960.fasta')
S2.seqs <- fasta2DNAbin('OROV_v_IQTV_S_BRA2000.fasta')
S3.seqs <- fasta2DNAbin('OROV_v_IQTV_S_BRA2009.fasta')
S4.seqs <- fasta2DNAbin('OROV_v_IQTV_S_PAN1999.fasta')
S5.seqs <- fasta2DNAbin('OROV_v_IQTV_S_ECU2016.fasta')
S6.seqs <- fasta2DNAbin('OROV_v_IQTV_S_PAN1989.fasta')
S7.seqs <- fasta2DNAbin('OROV_v_IQTV_S_PER2000.fasta')
S8.seqs <- fasta2DNAbin('OROV_v_IQTV_S_PER2008.fasta')

C1.seqs <- fasta2DNAbin('OROV_v_IQTV_Concat_BRA1960.fasta')
C2.seqs <- fasta2DNAbin('OROV_v_IQTV_Concat_BRA2000.fasta')
C3.seqs <- fasta2DNAbin('OROV_v_IQTV_Concat_BRA2009.fasta')
C4.seqs <- fasta2DNAbin('OROV_v_IQTV_Concat_PAN1999.fasta')
C5.seqs <- fasta2DNAbin('OROV_v_IQTV_Concat_ECU2016.fasta')
C6.seqs <- fasta2DNAbin('OROV_v_IQTV_Concat_PAN1989.fasta')
C7.seqs <- fasta2DNAbin('OROV_v_IQTV_Concat_PER2000.fasta')
C8.seqs <- fasta2DNAbin('OROV_v_IQTV_Concat_PER2008.fasta')

#Set sliding windows on alignments to estimate genetic distances
L1_wndws <- slidingWindow(L1.seqs, width = round(length(L1.seqs)*0.07), interval = 20)
length(L1_wndws)
L2_wndws <- slidingWindow(L2.seqs, width = round(length(L2.seqs)*0.07), interval = 20)
length(L2_wndws)
L3_wndws <- slidingWindow(L3.seqs, width = round(length(L3.seqs)*0.07), interval = 20)
length(L3_wndws)
L4_wndws <- slidingWindow(L4.seqs, width = round(length(L4.seqs)*0.07), interval = 20)
length(L4_wndws)
L5_wndws <- slidingWindow(L5.seqs, width = round(length(L5.seqs)*0.07), interval = 20)
length(L5_wndws)
L6_wndws <- slidingWindow(L6.seqs, width = round(length(L6.seqs)*0.07), interval = 20)
length(L6_wndws)
L7_wndws <- slidingWindow(L7.seqs, width = round(length(L7.seqs)*0.07), interval = 20)
length(L7_wndws)
L8_wndws <- slidingWindow(L8.seqs, width = round(length(L8.seqs)*0.07), interval = 20)
length(L8_wndws)

G1a_wndws <- slidingWindow(G1a.seqs, width = round(length(G1a.seqs)*0.07), interval = 20)
length(G1a_wndws)
G1b_wndws <- slidingWindow(G1b.seqs, width = round(length(G1b.seqs)*0.07), interval = 20)
length(G1b_wndws)
G1c_wndws <- slidingWindow(G1c.seqs, width = round(length(G1c.seqs)*0.07), interval = 20)
length(G1c_wndws)
G1d_wndws <- slidingWindow(G1d.seqs, width = round(length(G1d.seqs)*0.07), interval = 20)
length(G1d_wndws)
G2a_wndws <- slidingWindow(G2a.seqs, width = round(length(G2a.seqs)*0.07), interval = 20)
length(G2a_wndws)
G2b_wndws <- slidingWindow(G2b.seqs, width = round(length(G2b.seqs)*0.07), interval = 20)
length(G2b_wndws)
G2c_wndws <- slidingWindow(G2c.seqs, width = round(length(G2c.seqs)*0.07), interval = 20)
length(G2c_wndws)
G2d_wndws <- slidingWindow(G2d.seqs, width = round(length(G2d.seqs)*0.07), interval = 20)
length(G2d_wndws)

S1_wndws <- slidingWindow(S1.seqs, width = round(length(S1.seqs)*0.07), interval = 20)
length(S1_wndws)
S2_wndws <- slidingWindow(S2.seqs, width = round(length(S2.seqs)*0.07), interval = 20)
length(S2_wndws)
S3_wndws <- slidingWindow(S3.seqs, width = round(length(S3.seqs)*0.07), interval = 20)
length(S3_wndws)
S4_wndws <- slidingWindow(S4.seqs, width = round(length(S4.seqs)*0.07), interval = 20)
length(S4_wndws)
S5_wndws <- slidingWindow(S5.seqs, width = round(length(S5.seqs)*0.07), interval = 20)
length(S5_wndws)
S6_wndws <- slidingWindow(S6.seqs, width = round(length(S6.seqs)*0.07), interval = 20)
length(S6_wndws)
S7_wndws <- slidingWindow(S7.seqs, width = round(length(S7.seqs)*0.07), interval = 20)
length(S7_wndws)
S8_wndws <- slidingWindow(S8.seqs, width = round(length(S8.seqs)*0.07), interval = 20)
length(S8_wndws)

C1_wndws <- slidingWindow(C1.seqs, width = 600, interval = 20)
length(C1_wndws)
C2_wndws <- slidingWindow(C2.seqs, width = 600, interval = 20)
length(C2_wndws)
C3_wndws <- slidingWindow(C3.seqs, width = 600, interval = 20)
length(C3_wndws)
C4_wndws <- slidingWindow(C4.seqs, width = 600, interval = 20)
length(C4_wndws)
C5_wndws <- slidingWindow(C5.seqs, width = 600, interval = 20)
length(C5_wndws)
C6_wndws <- slidingWindow(C6.seqs, width = 600, interval = 20)
length(C6_wndws)
C7_wndws <- slidingWindow(C7.seqs, width = 600, interval = 20)
length(C7_wndws)
C8_wndws <- slidingWindow(C8.seqs, width = 600, interval = 20)
length(C8_wndws)